# config.py - configuration constants common to experiments.py and plot.py
#
# CS655 error control assignment
# Jeffrey Finkelstein
# November 2011
"""Provides constants which are common to both `experiments.py` and `plot.py`,
including, but not limited to, the total number of messages generated by the
sender, the average delay between generated messages, the size of the window
(in windowed protocols), the probabilities of loss and corruption to test, and
the number of trials.

"""
NUM_MESSAGES = 1000
"""The total number of messages to generate on the sender side."""

MESSAGE_DELAY = 40
"""The average delay between generated messages on the sender side."""

TRACE = -1
"""The level of verbosity in logged messages."""

WINDOWSIZE = 8
"""The size of the packet window in windowed protocols."""

TIMEOUT = 20
"""The retransmission timeout for the sender."""

PROTOCOLS = ('GBN', 'SR')
"""The protocols to test: `GBN` for "go back N" and `SR` for "selective repeat"."""

LOSS_PROBS = (0.0, 0.1, 0.2, 0.3, 0.4, 0.5)
"""The loss probabilities under which to run the simulation."""

CORRUPTION_PROBS = (0.0, 0.1, 0.2, 0.3, 0.4, 0.5)
"""The corruption probabilities under which to run the simulation."""

NUM_TRIALS, T_ALPHA = 5, 2.132
"""NUM_TRIALS is the total number of independent trials to run for each
combination of parameters.

T_ALPHA is a value necessary for computing confidence intervals.

The value of T_ALPHA depends on `NUM_TRIALS`, and half the confidence interval
percentage desired, and is looked up from the table at
http://people.hofstra.edu/Stefan_Waner/RealWorld/finitetopic1/t_table.html.

"""
